spring:
  datasource:
    url: jdbc:postgresql://db:5432/statementdb
    username: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/statement-service

statement:
  storage:
    base-dir: /data/files
